### ISSUE TITLE
Request: Is it possible to use Tauri instead of Electron?

### ISSUE THREAD

**Issue by BDVGitHub** [author-more/penpot-desktop#47]
Is it possible to use Tauri instead of Electron. In the install instructions, I saw that Electron is used. I know it will take a lot of work, but could you consider switching to Tauri? This is more performant in terms of security, results in less large install file, less memory consumption, a full comparison between Tauri and Electron can be found on the following site: [Tauri vs Electron](https://dev.to/dedsyn4ps3/goodbye-electron-hello-tauri-26d5)

**Comment by Belar** [comment]
Hello @BDVGitHub,
I’m open to use Tauri for Penpot Desktop and regularly check what’s the state of it. However, when Tauri brings compelling benefits, as you mentioned, the project so far benefited from their counterparts in Electron.

Electron is a mature ecosystem and a lot of problems have been solved by now. While it’s unfortunate that it ships a sizeable bundle, UI is uniform across platforms and feature availability is set. It has good embedding support (for now) and works well as a web app wrapper - something that is not priority of Tauri. Since I’m developing Penpot Desktop mostly myself, part-time, and sponsor its development, any time savings that can be achieved are precious from the perspective of the project.

I’m looking forward to giving Tauri another go. Current priorities allow us to not rush it though.
